SELECT
    inserted_date inserted_date,
    updated_date updated_date,
    [CONTACT_ID] 'Contact ID',
    [CONTACT_RECORD_CREATE_TIMESTAMP] [Contact Records Create Timestamp],
    [CONTACT_RECORD_MODIFIED_TIMESTAMP] [Contact Record Modified Timestamp],
    [CONTACT_IN_DNC] [Contact in DNC],
    [CUSTOMER_NAME] [Customer Name],
    number1 'Number1',
    number2 'Number2',
    number3 'Number3',
    first_name 'First Name',
    last_name 'Last Name',
    company 'Company',
    street 'Street',
    city 'City',
    state 'State',
    zip 'Zip',
    email 'Email',
    [ECLAccountName] [ECL Account Name],
    utility 'Utility',
    [secondUtility] [Second Utility],
    [secondaryContact] [Secondary Contact],
    [rateClass] [Rate Class],
    [TPVNumber] [TPV Number],
    accts 'Accts',
    [updatedName] [Updated Name],
    [updatedNumber] [Updated Number],
    [updatedStreet] [Updated Street],
    [updatedState] [Updated State],
    [updatedZip] [Updated Zip],
    [updatedCity] [Updated City],
    [uniqueKey] [Unique Key],
    next_ani 'Next Ani',
    [Mailing_Address] [Mailing Address],
    [lastList] [Last List],
    [forwardExtension] [Forward Extension],
    [contactRecordLastModified] [Contact Record Last Modified],
    [lastDisposition] [Last Disposition],
    [Contact_Created_Date] [Contact Created Date],
    [lastDispostionDateTime] [Last Dispostion Date Time],
    [Time2Dial] [Time 2 Dial],
    zip_group 'Zip Group',
    [CallbackAgent] [Callback Agent],
    [Customer_Called_In_No_one_answered_ReQue] [Customer Called In No one answeredReQue],
    [Notes] [Notes],
    [Disposition_Count] [Disposition Count],
    dialattempts [Dial Attempts],
    [Wireless_Flag] [Wireless Flag],
    [setCallbackTime] [Set Callback Time],
    [Wireless_Flag2] [Wireless Flag2],
    [Wireless_Flag3] [Wireless Flag3]
  FROM five9.GetContactDetailsReport c