SELECT post_request_id 'Post Request ID',
    phone_number 'Phone Number',
    lead_status 'Lead Status', 
    call_back_status 'Call Back Status',
    vici_post_status 'Vici Post Status', 
    customer_name 'Customer Nname',
    street 'Street',
    city 'City',
    zip 'Zip',
    state 'State',
    certificate_url 'Certificate URL',
    dm_name 'DM Name',
    utility 'Utility',
    call_back_url 'Call Back URL',
    vendor_code 'Vendor',
    rate_class 'Rate Class',
    mailing_street 'Mailing Street',
    mailing_city 'Mailing City',
    mailing_zip 'Mailing Zip',
    mailing_state 'Mailing State',
    vicidial_request_id 'VICIdial Request ID',
    response_raw_id 'Response Raw ID',
    request_id 'Request ID',
    error 'Error',
    call_back_error 'Call Back Error',
    vici_post_error 'vici_post_error',
    vendor_campaign_name 'Campaign name', 
    target_vicidial_list_id 'Target VICIdial List ID',
    TargetListName_f9 'Target List Name f9',
    inserted_date 'Date Inserted',
    updated_date 'Date Updated'
FROM dbo.post_request 