SELECT CallLogApiSync_id,
    response_raw_id,
    load_status 'Load Status',
    request_id,
    call_id,
    timestamp 'Timestamp',
    campaign 'Campaign',
    call_type 'Call Type',
    agent 'Agent Email',
    agent_name 'Agent',
    disposition 'Disposition',
    ani,
    customer_name 'Customer Name',
    dnis,
    call_time,
    bill_time_rounded,
    cost,
    ivr_time,
    queue_wait_time,
    ring_time,
    talk_time,
    hold_time,
    park_time,
    after_call_work_time,
    transfers,
    conferences,
    holds,
    abandoned,
    recordings,
    dial_result,
    list_name 'List Name',
    agent_id,
    contact_id,
    last_name,
    rateclass 'Rate Class',
    lastdisposition,
    first_name,
    contact_modified_timestamp,
    number1,
    number2,
    number3,
    secondarycontact,
    uniquekey,
    last_disposition,
    contact_create_timestamp,
    contactrecordlastmodified,
    inserted_date,
    updated_date,
    ecl_account_name,
    company
  FROM five9.CallLogApiSync