SELECT [CONTACT ID] [Contact ID], 
    COUNT(DISTINCT [LIST RECORD ID]) [Lists], 
    COUNT(DISTINCT [CAMPAIGN]) [Campaigns]
FROM five9.GetListDetailsReport
GROUP BY [CONTACT ID]
HAVING COUNT(DISTINCT [LIST RECORD ID]) > 1 
    OR COUNT(DISTINCT [CAMPAIGN]) > 1 